---
title: 'SDS 322E Project: Aging Biomarkers'
author: Erin Pennington, Bella Vincent, Janice Oh, Anthony Tang, James Groh, Jilliane
  Lagus
date: "10/25/2021"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Title
Aging Biomarkers 

## Project Description
Our project goals are to explore the relationships between biomarkers or other survey data and age.

In the first part we plan to explore aspects such as socioeconomic status and demographics in relation to age, age categories, or biomarkers such as blood pressure, oral health, etc.

Our tentative plan for the second part is to determine significant biomarkers that can be used in a regression to predict the biological age of an individual. For example, perhaps a marker such as blood pressure might indicate that a person might be at risk for suffering age-related complications sooner in life.

## Link to Dataset
https://wwwn.cdc.gov/nchs/nhanes/continuousnhanes/default.aspx?BeginYear=2017

## Dataset Description
The National Health and Nutrition Examination Survey (NHANES) contains multiple studies assessing health and nutrition of adults and children in the United States. It offers a number of different data files containing interview results and physical examinations, for example lab test results.

We will be downloading a subset of these data files for our exploratory analysis based on which variables are interesting to us.

# Additional Info
This review article provided the inspiration for determining biological age as a function of biomarkers available from test results. Their methods will differ from ours, but it provides some starting points for which biomarkers might be of interest to us.

https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6599717/

# Github Repository
https://github.com/epenning/aging-biomarkers.git
